[env:esp8266]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dout

lib_deps =
    ESP8266WiFi
    ESP8266mDNS

build_flags =
    -DLIDAR_BAUD=115200
    -DENCODER_PIN_A=4
    -DENCODER_PIN_B=5
    -DMOTOR_PWM_PIN=14
    -DMOTOR_DIR_PIN=12
    -DPPR=400
    -DWIFI_SSID="\"your-ssid\""
    -DWIFI_PASS="\"your-password\""
    -DTCP_PORT=23
